#//
#// (c) Copyright 2012 - 2024 HP Development Company, L.P.
#// This software and associated documentation (if any) is furnished under a license and may only be used or
#// copied in accordance with the terms of the license. Except as permitted by such license, no part of this
#// software or documentation may be reproduced, stored in a retrieval system, or transmitted in any
#// form or by any means without the express written consent of HP Development Company.
#//
#// Prepare build tokens for EDKII
#//

[BuildOptions]

#
# SA
#
!if gSiPkgTokenSpaceGuid.PcdBdatEnable == TRUE
   DEFINE BDAT_BUILD_OPTION = -DBDAT_SUPPORT=1
!else
   DEFINE BDAT_BUILD_OPTION =
!endif

!if gSiPkgTokenSpaceGuid.PcdVtdEnable == TRUE
   DEFINE DSC_VTD_BUILD_OPTIONS = /DVTD_SUPPORT_FLAG=1
!else
   DEFINE DSC_VTD_BUILD_OPTIONS =
!endif

!if gSiPkgTokenSpaceGuid.PcdTxtEnable == TRUE
   DEFINE DSC_TXT_BUILD_OPTIONS = /DTXT_SUPPORT_FLAG=1
!else
   DEFINE DSC_TXT_BUILD_OPTIONS =
!endif

!if gSiPkgTokenSpaceGuid.PcdAmtEnable == TRUE
   DEFINE AMT_BUILD_OPTION = /DAMT_SUPPORT=1
!else
   DEFINE AMT_BUILD_OPTION =
!endif

!if gSiPkgTokenSpaceGuid.PcdStatusCodeUseTraceHub == TRUE
   DEFINE TRACE_HUB_ENABLE_BUILD_OPTIONS = /DTRACE_HUB_ENABLE=1
   DEFINE TRACE_HUB_DEBUG_BUILD_OPTIONS = /DTRACE_HUB_DEBUG_ENABLE=1
!else
   DEFINE TRACE_HUB_ENABLE_BUILD_OPTIONS =
   DEFINE TRACE_HUB_DEBUG_BUILD_OPTIONS =
!endif

!if gSiPkgTokenSpaceGuid.PcdFspBinaryEnable == FALSE
   DEFINE DSC_FSP_SUPPORT = /DHP_FSP_WRAPPER_FLAG=1 /DFSP_WRAPPER_FLAG=1
!else
   DEFINE DSC_FSP_SUPPORT =
!endif

!if gSiPkgTokenSpaceGuid.PcdMtlSSupport == TRUE
  DEFINE MTLS_BUILD_OPTION = -DMTLS_SUPPORT=1
  DEFINE PCH_SERIES_S = /DPCH_SERIES_S=1
  DEFINE GPIOV2_COMMON_PATH = /D GPIOV2_COMMON_PATH="\_SB.PGPI"
!else
  DEFINE MTLS_BUILD_OPTION =
  DEFINE PCH_SERIES_S =
  DEFINE GPIOV2_COMMON_PATH = /D GPIOV2_COMMON_PATH="\_SB"
!endif

#
# gEfiHpFeatureMiscPubIntPkgTokenSpaceGuid
#
!if gEfiHpFeatureMiscPubIntPkgTokenSpaceGuid.PcdVPEnable == TRUE
   DEFINE VP_BUILD_OPTIONS = /DVP_FLAG
!else
   DEFINE VP_BUILD_OPTIONS =
!endif

!if (gEfiHpFeatureMiscPubIntPkgTokenSpaceGuid.PcdSLEEnable == TRUE) OR ($(RELEASE_BUILD_DEBUG) == TRUE)
   DEFINE PDB_BUILD_OPTION = /Zi
!else
   DEFINE PDB_BUILD_OPTION =
!endif

!if gHpIntelChipsetPkgTokenSpaceGuid.PcdSerialDebugInAcpiEnable  == TRUE
   DEFINE DSC_SERIAL_DEBUG_SUPPORT = /DSERIAL_DEBUG=1
!else
   DEFINE DSC_SERIAL_DEBUG_SUPPORT =
!endif


#
# gHpIntelChipsetPkgTokenSpaceGuid
#
!if $(TARGET) == RELEASE
!if gHpIntelChipsetPkgTokenSpaceGuid.PcdIntelRvpSetupEnable== TRUE
  DEFINE DEBUG_BUILD_OPTIONS =
!else
  # MDEPKG_NDEBUG is introduced for the intention
  # of size reduction when compiler optimization is disabled. If MDEPKG_NDEBUG is
  # defined, then debug and assert related macros wrapped by it are the NULL implementations.
  DEFINE DEBUG_BUILD_OPTIONS = -DMDEPKG_NDEBUG -DNDEBUG
!endif
!else
  DEFINE DEBUG_BUILD_OPTIONS =
!endif

!if gHpIntelChipsetPkgTokenSpaceGuid.PcdHpVtioSupport == TRUE
   DEFINE DSC_HP_VTIO_SUPPORT = /DHP_VTIO_SUPPORT=1
!else
   DEFINE DSC_HP_VTIO_SUPPORT =
!endif

#
# gHpModernStandbyPkgTokenSpaceGuid, gHpMobilePkgTokenSpaceGuid
#
!if gHpModernStandbyPkgTokenSpaceGuid.PcdHpModernStandbySupport == TRUE
   DEFINE DSC_MODERN_STANDBY_SUPPORT = /DHP_MODERN_STANDBY_SUPPORTED
!else
   DEFINE DSC_MODERN_STANDBY_SUPPORT
!endif

!if gEfiBuiltInDeviceOptionsPubIntPkgTokenSpaceGuid.PcdCameraType == 1
  DEFINE DSC_MIPI_FRONT_CAMERA = /DMIPI_FRONT_CAMERA=1
!else
  DEFINE DSC_MIPI_FRONT_CAMERA =
!endif
# HPTODO is this used
!if gSiPkgTokenSpaceGuid.PcdTxtEnable == TRUE
   DEFINE DSC_TXT_BUILD_OPTIONS = /DTXT_SUPPORT_FLAG=1
!else
   DEFINE DSC_TXT_BUILD_OPTIONS =
!endif

!if $(ME_ENABLE) == TRUE
   DEFINE DSC_ME_BUILD_OPTIONS = /DME_SUPPORT_FLAG=1 /DiME_SUPPORT=1 /DICC_SUPPORT_FLAG=1
!else
   DEFINE DSC_ME_BUILD_OPTIONS =
!endif

# HPTODO: Are the following entries needed for Gondor?
# HPTODO: Everything from here down to "For HP build env variable end" comment is suspect

# Duke - For HP build env variable start

!if $(HP_ESPI_BUS_SUPPORT) == TRUE
   DEFINE DSC_ESPI_BUS_SUPPORT = /DESPI_BUS_SUPPORT=1
!else
   DEFINE DSC_ESPI_BUS_SUPPORT = /DESPI_BUS_SUPPORT=0
!endif

!if $(HP_ANTI_THEFT_SUPPORT) == TRUE
   DEFINE DSC_ANTI_THEFT_SUPPORT = /DANTI_THEFT_SUPPORT=1
!else
   DEFINE DSC_ANTI_THEFT_SUPPORT = /DANTI_THEFT_SUPPORT=0
!endif

!if $(BIOS_AUDIT_LOG_SUPPORT) == TRUE
   DEFINE DSC_BIOS_AUDIT_LOG_SUPPORT = /DBIOS_AUDIT_LOG_SUPPORT=1
!else
   DEFINE DSC_BIOS_AUDIT_LOG_SUPPORT = /DBIOS_AUDIT_LOG_SUPPORT=0
!endif

!if $(OFFICIAL_RELEASE) == TRUE
   DEFINE DSC_SIGNING_KEYS   = /DOFFICIAL_RELEASE=1 /DSECURITY_FLAGS_INCLUDED
!else
   DEFINE DSC_SIGNING_KEYS   = /DOFFICIAL_RELEASE=0 /DSECURITY_FLAGS_INCLUDED
!endif

!if $(CONNECTED_BIOS_ENABLED) == TRUE
   DEFINE DSC_CONNECTED_BIOS_ENABLED   = /DCONNECTED_BIOS_ENABLED=1
!else
   DEFINE DSC_CONNECTED_BIOS_ENABLED   = /DCONNECTED_BIOS_ENABLED=0
!endif

!if $(HP_WAKE_ON_LAN_SUPPORT) == TRUE
   DEFINE DSC_HP_WAKE_ON_LAN_SUPPORT = /DHP_WAKE_ON_LAN_SUPPORT=1
!else
   DEFINE DSC_HP_WAKE_ON_LAN_SUPPORT =
!endif



  DEFINE DSC_EDK2_PI_SPEC = /DPI_SPECIFICATION_VERSION=0x0001001E

# Duke - For HP build env variable end

!if $(DEBUG_MESSAGE_ENABLE) == TRUE
   DEFINE DEBUG_BUILD_OPTIONS = /D EFI_DEBUG /D DEBUG_MODE=1 /DEDKII_GLUE_DebugPrintErrorLevel=(EFI_D_LOAD+EFI_D_ERROR+EFI_D_INFO+EFI_D_WARN+EFI_D_EVENT)
!endif

!if $(EFI_GENERATE_INTERMEDIATE_FILE) == TRUE
   DEFINE DSC_INTERMEDIATE_FILE = /FAsc
!else
   DEFINE DSC_INTERMEDIATE_FILE =
!endif


!if $(OPTIMIZE_COMPILER_ENABLE) == FALSE
   DEFINE OPTIMIZE_DISABLE_OPTIONS = /Od /GL-
!endif



!if $(USB_TYPE_C_SUPPORT) == TRUE
   DEFINE DSC_USB_TYPE_C_SUPPORT_OPTIONS = /DUSB_TYPE_C_SUPPORT=1
!else
   DEFINE DSC_USB_TYPE_C_SUPPORT_OPTIONS = /DUSB_TYPE_C_SUPPORT=0
!endif

!if $(HP_USB_TYPE_C_CCG4_SUPPORT) == TRUE
   DEFINE DSC_HP_USB_TYPE_C_CCG4_SUPPORT_OPTIONS = /DHP_USB_TYPE_C_CCG4_SUPPORT=1
!else
   DEFINE DSC_HP_USB_TYPE_C_CCG4_SUPPORT_OPTIONS = /DHP_USB_TYPE_C_CCG4_SUPPORT=0
!endif

!if $(FINGERPRINT_SUPPORT) == TRUE
   DEFINE DSC_FINGERPRINT_SUPPORT = /DFINGERPRINT_SUPPORT=1
!else
   DEFINE DSC_FINGERPRINT_SUPPORT = /DFINGERPRINT_SUPPORT=0
!endif

!if $(DUST_FILTER_SUPPORT) == TRUE
   DEFINE DSC_DUST_FILTER_SUPPORT = /DDUST_FILTER_SUPPORT=1
!else
   DEFINE DSC_DUST_FILTER_SUPPORT = /DDUST_FILTER_SUPPORT=0
!endif


!if $(HP_KEYBOARD_POWER_ON_SUPPORT) == TRUE
   DEFINE DSC_HP_KEYBOARD_POWER_ON_SUPPORT = /DHP_KEYBOARD_POWER_ON_SUPPORT=1
!else
   DEFINE DSC_HP_KEYBOARD_POWER_ON_SUPPORT =
!endif
!if $(NETWORK_OS_RECOVERY_SUPPORT) == TRUE
  DEFINE DSC_NETWORK_OS_RECOVERY_SUPPORT = /DNETWORK_OS_RECOVERY_SUPPORT=1
!else
  DEFINE DSC_NETWORK_OS_RECOVERY_SUPPORT = /DNETWORK_OS_RECOVERY_SUPPORT=0
!endif

#!if gSiPkgTokenSpaceGuid.PcdSkycamEnable == TRUE
#   DEFINE DSC_SKYCAM_SUPPORT = /DSKYCAM_SUPPORT=1
#!else
#   DEFINE DSC_SKYCAM_SUPPORT = /DSKYCAM_SUPPORT=0
#!endif

!if $(SERIAL_IO_ENABLE) == TRUE
   DEFINE DSC_SERIAL_IO_SUPPORT = /DSERIALIO_SUPPORT=1
!else
   DEFINE DSC_SERIAL_IO_SUPPORT = /DSERIALIO_SUPPORT=0
!endif

!if $(RESTRICT_USB_DEVICES_SUPPORT) == TRUE
   DEFINE DSC_RESTRICT_USB_DEVICES_SUPPORT = /DRESTRICT_USB_DEVICES_SUPPORT=1
!else
   DEFINE DSC_RESTRICT_USB_DEVICES_SUPPORT = /DRESTRICT_USB_DEVICES_SUPPORT=0
!endif

!if $(SECURE_BOOT_ENABLE) == TRUE
   DEFINE DSC_SECURE_BOOT_ENABLE = /DSECURE_BOOT_ENABLE=1
!else
   DEFINE DSC_SECURE_BOOT_ENABLE = /DSECURE_BOOT_ENABLE=0
!endif

!if $(FSP_DEBUG_IN_RELEASE_MODE) == TRUE
   DEFINE DSC_FSP_DEBUG_IN_RELEASE_MODE = /DFSP_DEBUG_IN_RELEASE_MODE=1
!else
   DEFINE DSC_FSP_DEBUG_IN_RELEASE_MODE =
!endif

!if gPlatformModuleTokenSpaceGuid.PcdSinitAcmBinEnable == TRUE
   DEFINE SINITBIN_BUILD_OPTION = -DSINITBIN_FLAG=1
!else
   DEFINE SINITBIN_BUILD_OPTION =
!endif


   DEFINE MINTREE_FLAG_BUILD_OPTION = -DMINTREE_FLAG=1

!if $(HP_VPM_SUPPORT) == TRUE
   DEFINE DSC_HP_VPM_SUPPORT_OPTIONS = /DHP_VPM_SUPPORT=1
!else
   DEFINE DSC_HP_VPM_SUPPORT_OPTIONS = /DHP_VPM_SUPPORT=0
!endif

!if $(HP_SUPER_VPM_SUPPORT) == TRUE
   DEFINE DSC_HP_SUPER_VPM_SUPPORT_OPTIONS = /DHP_SUPER_VPM_SUPPORT=1
!else
   DEFINE DSC_HP_SUPER_VPM_SUPPORT_OPTIONS = /DHP_SUPER_VPM_SUPPORT=0
!endif

!if $(HP_SIO_PRIVACY_PANEL_SUPPORT) == TRUE
   DEFINE DSC_HP_SIO_PRIVACY_PANEL_SUPPORT = /DHP_SIO_PRIVACY_PANEL_SUPPORT=1
!else
   DEFINE DSC_HP_SIO_PRIVACY_PANEL_SUPPORT =
!endif

!if $(HP_SCALAR_PRIVACY_PANEL_SUPPORT) == TRUE
   DEFINE DSC_HP_SCALAR_PRIVACY_PANEL_SUPPORT = /DHP_SCALAR_PRIVACY_PANEL_SUPPORT=1
!else
   DEFINE DSC_HP_SCALAR_PRIVACY_PANEL_SUPPORT =
!endif

!if gEfiSioTokenSpaceGuid.PcdDGpuVpmSupport == TRUE
   DEFINE DSC_DGPU_VPM_SUPPORT_OPTIONS = /DDGPU_VPM_SUPPORT=1
!else
   DEFINE DSC_DGPU_VPM_SUPPORT_OPTIONS = /DDGPU_VPM_SUPPORT=0
!endif

!if $(HP_RPOS_PLATFORM) == TRUE
   DEFINE DSC_HP_RPOS_PLATFORM = /DHP_RPOS_PLATFORM=1
!else
   DEFINE DSC_HP_RPOS_PLATFORM = /DHP_RPOS_PLATFORM=0
!endif

DEFINE HP_SERIES_BUILD_OPTION = /DHP_SERIES=$(HP_SERIES)
DEFINE HP_PROJECT_DEFINITION_BUILD_OPTION = $(HP_PROJECT_DEFINITION)
DEFINE HP_SERIES_BUILD_OPTION = /DHP_SERIES=$(HP_SERIES)
DEFINE HP_SERIES_DEFINITION_BUILD_OPTION = $(HP_SERIES_DEFINITION)



!if $(INTEL_PLATFORM) == TRUE
  DEFINE DSC_INTEL_SILICON_REVISION = /DINTEL_SILICON_REVISION=$(INTEL_SILICON_REVISION)
!else
  DEFINE DSC_INTEL_SILICON_REVISION =
!endif
!if gHpIntelChipsetPkgTokenSpaceGuid.PcdFspDebug == TRUE
  DEFINE DSC_FSP_DEBUG = /DFSP_DEBUG=1
!else
  DEFINE DSC_FSP_DEBUG =
!endif

!if $(INTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT) == TRUE
   DEFINE DSC_INTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT = /DINTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT=1
!else
   DEFINE DSC_INTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT = /DINTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT=0
!endif

!if $(INTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT) == TRUE
   DEFINE DSC_INTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT = /DINTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT=1
!else
   DEFINE DSC_INTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT = /DINTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT=0
!endif

!ifdef BIOS_REGION_SIZE
   DEFINE DSC_BIOS_REGION_SIZE = /DBIOS_REGION_SIZE=$(BIOS_REGION_SIZE)
!endif

DEFINE CPU_FLAGS = -DCPU_ICL -DCPU_TGL -DCPU_ADL

DEFINE DSC_SIPKG_FEATURE_BUILD_OPTIONS = $(CPU_FLAGS) $(MTLS_BUILD_OPTION) $(PCH_SERIES_S) $(GPIOV2_COMMON_PATH)
DEFINE DSC_SIPKG_FEATURE_BUILD_OPTIONS = $(DSC_SIPKG_FEATURE_BUILD_OPTIONS) $(BDAT_BUILD_OPTION) $(DEBUG_BUILD_OPTIONS) $(DSC_SSA_BUILD_OPTIONS) $(SINITBIN_BUILD_OPTION) $(MINTREE_FLAG_BUILD_OPTION) $(DSC_FSP_DEBUG)
DEFINE DSC_HP_COMMON_BUILD_OPTIONS = $(HP_SERIES_BUILD_OPTION) $(DSC_USB_SD_SUPPORT) $(DSC_INTERMEDIATE_FILE) $(DEBUG_BUILD_OPTIONS) $(DSC_AGERE1394_SUPPORT) $(DSC_SIGNING_KEYS) $(DSC_CONNECTED_BIOS_ENABLED) $(DSC_USB_SD_SUPPORT) $(DSC_HP_SMBIOS_TYPE1_WAKEUP_LAN_FLAG) $(DSC_HP_PCIE_MEDIA_CARD_READER_SUPPORT) $(DSC_HP_SECONDARY_BATTERY_SUPPORT) $(DSC_FINGERPRINT_SUPPORT) $(DSC_DUST_FILTER_SUPPORT) $(DSC_ESPI_BUS_SUPPORT) $(DSC_HP_KEYBOARD_POWER_ON_SUPPORT) $(DSC_HP_DEEPS3_SUPPORT) $(DSC_DETACHABLE_SYSTEM_ENABLED) $(DSC_SKYCAM_SUPPORT) $(DSC_SERIAL_IO_SUPPORT) $(DSC_HP_LAN_WLAN_SWITCH_8260_SUPPORT) $(DSC_RESTRICT_USB_DEVICES_SUPPORT) $(DSC_USB_TYPE_C_SUPPORT_OPTIONS) $(DSC_HP_USB_TYPE_C_CCG4_SUPPORT_OPTIONS) $(DSC_PEAK_SHIFT_SUPPORT) $(DSC_MODERN_STANDBY_SUPPORT) $(DSC_SIPKG_FEATURE_BUILD_OPTIONS) $(DSC_SECURE_BOOT_ENABLE) $(DSC_SOURCE_DEBUG_BUILD_OPTIONS) $(DSC_HP_VPM_SUPPORT_OPTIONS) $(DSC_HP_SUPER_VPM_SUPPORT_OPTIONS) $(DSC_HP_RPOS_PLATFORM) $(DSC_CHIPSET_ADVANCED_SETUP_OPTION) $(DSC_DT_BUILD_OPTIONS) $(DSC_HP_MICROPHONE_LOCK_MODE) $(DSC_DGPU_VPM_SUPPORT_OPTIONS) $(DSC_INTEL_SILICON_REVISION) $(DSC_HP_VTIO_SUPPORT)  $(DSC_HP_SIO_PRIVACY_PANEL_SUPPORT) $(DSC_HP_SCALAR_PRIVACY_PANEL_SUPPORT) $(HP_PROJECT_DEFINITION_BUILD_OPTION) $(HP_SERIES_BUILD_OPTION) $(HP_SERIES_DEFINITION_BUILD_OPTION) $(DSC_INTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT) $(DSC_INTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT) $(DSC_BIOS_REGION_SIZE)
DEFINE DSC_HP_FEATURE_PLATFORM_BUILD_OPTIONS = $(DSC_SYSTEM_OPTIONS_PLATFORM_BUILD_OPTIONS) $(DSC_PORT_OPTIONS_PLATFORM_BUILD_OPTIONS) $(DSC_POWER_MANAGEMENT_PLATFORM_BUILD_OPTIONS) $(DSC_HP_GFX_MISC_PLATFORM_BUILD_OPTIONS) $(DSC_HP_BRIGHTNESS_PLATFORM_BUILD_OPTIONS) $(DSC_INTEL_HYBRID_GRAPHICS_PLATFORM_BUILD_OPTIONS) $(DSC_ADDON_GFX_POLICY_PLATFORM_BUILD_OPTIONS) $(DSC_AIO_GFX_POLICY_PLATFORM_BUILD_OPTIONS)
DEFINE DSC_HP_EDKII_BUILD_OPTIONS = $(DSC_S3_BUILD_OPTIONS)  $(DSC_EDK2_PI_SPEC) $(DSC_HP_DEEPS3_SUPPORT) $(DSC_MODERN_STANDBY_SUPPORT) $(DSC_PLTPKG_FEATURE_BUILD_OPTIONS) $(DSC_SIPKG_FEATURE_BUILD_OPTIONS) $(DSC_FSP_SUPPORT) $(DSC_FSP_DEBUG_IN_RELEASE_MODE)

!include NetworkPkg/NetworkBuildOptions.dsc.inc

# Define Build Options both for EDK and EDKII drivers.

   DEFINE TRAD_BUILD_OPTION = /DTRAD_FLAG=1

!if gSiPkgTokenSpaceGuid.PcdAmtEnable == TRUE
   DEFINE AMT_BUILD_OPTION = /DAMT_SUPPORT=1
!else
   DEFINE AMT_BUILD_OPTION =
!endif

!if ( $(ADSP_ENABLE) == TRUE )
   DEFINE ADSP_BUILD_OPTION = /DADSP_FLAG=1
!else
   DEFINE ADSP_BUILD_OPTION =
!endif

!if gSiPkgTokenSpaceGuid.PcdBdatEnable == TRUE
   DEFINE BDAT_BUILD_OPTION = -DBDAT_SUPPORT=1
!else
   DEFINE BDAT_BUILD_OPTION =
!endif

!if ( $(USB_PRECONDITION_ENABLE) == TRUE )
   DEFINE USB_PRECONDITION_BUILD_OPTION = /DUSB_PRECONDITION_ENABLE_FLAG=1
!else
   DEFINE USB_PRECONDITION_BUILD_OPTION =
!endif

!if $(GROUP_GPIO_SUPPORT) == TRUE
   DEFINE GROUP_GPIO_BUILD_OPTION = /DGROUP_GPIO=1
!else
   DEFINE GROUP_GPIO_BUILD_OPTION =
!endif

!if $(HP_MEMORY_DOWN_SUPPORT) == TRUE
   DEFINE MEMORY_DOWN_OPTION = /DMEMORY_DOWN_SUPPORT=1
!else
   DEFINE MEMORY_DOWN_OPTION =
!endif

!if gSiPkgTokenSpaceGuid.PcdBootGuardEnable == TRUE
   DEFINE HP_BOOT_GUARD = /DBOOTGUARD_ENABLED=1
!else
   DEFINE HP_BOOT_GUARD =
!endif
!if gEfiHpFeatureMiscPubIntPkgTokenSpaceGuid.PcdVPEnable == TRUE
   DEFINE VP_BUILD_OPTIONS = /DVP_FLAG
!else
   DEFINE VP_BUILD_OPTIONS =
!endif
DEFINE BIOS_BUILD_OPTIONS = $(INTEL_CHIPSET_ACPI_PATH) $(INTEL_CHIPSET_BUILD_OPTIONS) $(GFX_BUILD_OPTIONS) $(GFX_ACPI_PATH) $(TRAD_BUILD_OPTION) $(LPSS_BUILD_OPTION) $(ADSP_BUILD_OPTION) $(DSC_SSA_BUILD_OPTION) $(PEG_BUILD_OPTION) $(DMI_BUILD_OPTION) $(AMT_BUILD_OPTION) $(USB_PRECONDITION_BUILD_OPTION) $(DOCK_BUILD_OPTION) $(MEMORY_DOWN_OPTION) $(HP_TBT_BUILD_OPTIONS) $(GROUP_GPIO_BUILD_OPTION) $(CONDEV_ACPI_PATH) $(THERMAL_ACPI_PATH) $(HP_DPTF_BUILD_OPTION) $(HP_STORAGE_BUILD_OPTIONS) $(HP_BOOT_GUARD) $(DMAR_PKG_BUILD_OPTIONS)

!if $(PFAT_EC_ENABLE) == TRUE
   DEFINE PFAT_BUILD_OPTION = /DPFAT_EC_FLAG=1
!else
   DEFINE PFAT_BUILD_OPTION =
!endif

!if $(ANC_ENABLE) == TRUE
   DEFINE ANC_BUILD_OPTIONS = /DANC_SUPPORT_FLAG=1
!else
   DEFINE ANC_BUILD_OPTIONS =
!endif

!if $(VTX_ENABLE) == TRUE
   DEFINE DSC_VTX_BUILD_OPTIONS = /DVTX_SUPPORT_FLAG=1
!else
   DEFINE DSC_VTX_BUILD_OPTIONS =
!endif

!if gSiPkgTokenSpaceGuid.PcdVtdEnable == TRUE
   DEFINE DSC_VTD_BUILD_OPTIONS = /DVTD_SUPPORT_FLAG=1
!else
   DEFINE DSC_VTD_BUILD_OPTIONS =
!endif

!if gSiPkgTokenSpaceGuid.PcdTxtEnable == TRUE
   DEFINE DSC_TXT_BUILD_OPTIONS = /DTXT_SUPPORT_FLAG=1 /DTXT_FLAG=1
!else
   DEFINE DSC_TXT_BUILD_OPTIONS =
!endif

!if gHpIntelChipsetPkgTokenSpaceGuid.PcdFeatureBytevProUpsellSupport == TRUE
   DEFINE DSC_VPRO_UPSELL_BUILD_OPTIONS = /DVPRO_UPSELL_SUPPORT_FLAG=1
!else
   DEFINE DSC_VPRO_UPSELL_BUILD_OPTIONS =
!endif

!if gHpIntelChipsetPkgTokenSpaceGuid.PcdIntelMeOptionRemovalEnable == TRUE
   DEFINE DSC_ME_OPTION_REMOVE_BUILD_OPTIONS = /DME_OPTION_REMOVE_FLAG=1
!else
   DEFINE DSC_ME_OPTION_REMOVE_BUILD_OPTIONS =
!endif

!if gSiPkgTokenSpaceGuid.PcdStatusCodeUseTraceHub == TRUE
   DEFINE TRACE_HUB_ENABLE_BUILD_OPTIONS = /DTRACE_HUB_ENABLE=1
   DEFINE TRACE_HUB_DEBUG_BUILD_OPTIONS = /DTRACE_HUB_DEBUG_ENABLE=1
!else
   DEFINE TRACE_HUB_ENABLE_BUILD_OPTIONS =
   DEFINE TRACE_HUB_DEBUG_BUILD_OPTIONS =
!endif

!if (gEfiHpFeatureMiscPubIntPkgTokenSpaceGuid.PcdSLEEnable == TRUE) OR ($(RELEASE_BUILD_DEBUG) == TRUE)
   DEFINE PDB_BUILD_OPTION = /Zi
!else
   DEFINE PDB_BUILD_OPTION =
!endif


# HP: Redefined here, but with more options (came from Intel this way)
#HP Specific+ TracHubDebug-start
DEFINE EDK_EDKII_DSC_FEATURE_BUILD_OPTIONS = $(PDB_BUILD_OPTION) $(TEST_MENU_BUILD_OPTION) $(VP_BUILD_OPTIONS) $(BIOS_BUILD_OPTIONS) $(PFAT_BUILD_OPTION) $(DSC_VTX_BUILD_OPTIONS) $(DSC_VTD_BUILD_OPTIONS) $(DSC_TXT_BUILD_OPTIONS) $(DSC_VPRO_UPSELL_BUILD_OPTIONS) $(DSC_ME_OPTION_REMOVE_BUILD_OPTIONS) $(TRACE_HUB_DEBUG_BUILD_OPTIONS) $(BDAT_BUILD_OPTION)
#HP Specific- TracHubDebug-end

!if gSiPkgTokenSpaceGuid.PcdSourceDebugEnable == TRUE
   *_*_X64_GENFW_FLAGS  = --keepexceptiontable
!endif

## 4K alignment for DXE image protection
[BuildOptions.common.EDKII.DXE_CORE,BuildOptions.common.EDKII.DXE_DRIVER,BuildOptions.common.EDKII.UEFI_DRIVER,BuildOptions.common.EDKII.UEFI_APPLICATION]
  MSFT:*_*_*_DLINK_FLAGS = /ALIGN:4096

## 4K alignment for UEFI NX/ RT memory attributes table
[BuildOptions.common.EDKII.DXE_RUNTIME_DRIVER]
   MSFT:*_*_*_DLINK_FLAGS = /ALIGN:4096

## 4K alignment for SS3 / SMM memory attributes table
[BuildOptions.X64.EDKII.DXE_SMM_DRIVER]
   MSFT:*_*_*_DLINK_FLAGS = /ALIGN:4096

## 4K alignment for SS3 / SMM memory attributes table
[BuildOptions.X64.EDKII.SMM_CORE]
   MSFT:*_*_*_DLINK_FLAGS = /ALIGN:4096

# Set the Build Options for network drivers.
!if $(CONNECTED_BIOS_ENABLED) == TRUE
[BuildOptions.common]
   MSFT:*_*_*_CC_FLAGS = /DINCLUDE_DRIVER_BINDING
#  GCC:*_*_*_CC_FLAGS =
!endif

# Set the Build Options for EDKII drivers.
[BuildOptions.Common.EDKII]
   !include $(HP_CORE)/HpCoreBuildOptions.dsc
   !include $(HP_FEATURE)/HpFeatureBuildOptions.dsc
   !include $(HP_CHIPSET_PACKAGE)/HpFeature/HpFeatureChipsetBuildOptions.dsc
!if $(RELEASE_BUILD_DEBUG) == TRUE
   RELEASE_*_*_DLINK_FLAGS = /DEBUG
!endif

#
# For Xcode Specific Build Flag
#
# Override assembly code build order
*_XCODE5_*_*_BUILDRULEORDER = nasm S s
# Align 47bfbd7f8069e523798ef973c8eb0abd5c6b0746 to fix the usage of VA_START in undefined way
*_XCODE5_*_CC_FLAGS = -Wno-varargs

   DEFINE SV_EDKII_BUILD_OPTIONS = $(DSC_HP_CORE_BUILD_OPTIONS) $(DSC_HP_COMMON_BUILD_OPTIONS) $(DSC_HP_EDKII_BUILD_OPTIONS) $(DSC_HP_FEATURE_BUILD_OPTIONS) $(DSC_HP_FEATURE_CHIPSET_BUILD_OPTIONS) $(DSC_HP_FEATURE_PLATFORM_BUILD_OPTIONS)
   DEFINE SV_EDKII_TEST_MENU_BUILD_OPTION =
   DEFINE CPURC_BUILD_OPTION =
   DEFINE EDKII_DSC_BUILD_OPTIONS = $(EDK_EDKII_DSC_FEATURE_BUILD_OPTIONS) $(SV_EDKII_BUILD_OPTIONS) $(SV_EDKII_TEST_MENU_BUILD_OPTION) $(CPURC_BUILD_OPTION)

   *_*_IA32_ASM_FLAGS     = $(VP_BUILD_OPTIONS) $(BIOS_BUILD_OPTIONS) $(ANC_BUILD_OPTIONS) /D PLATFORM_PCIEXPRESS_LENGTH=$(PLATFORM_PCIEXPRESS_LEN)h /D EDKII_GLUE_PciExpressBaseAddress=$(PLATFORM_PCIEXPRESS_BASE)h /D PCIEX_LENGTH_BIT_SETTING=$(PLATFORM_PCIEX_LENGTH_BIT_SETTING)b $(DSC_P21_SUPPORT)

  *_*_IA32_CC_FLAGS      = $(EDKII_DSC_BUILD_OPTIONS) /D PLATFORM_PCIEXPRESS_BASE=0x$(PLATFORM_PCIEXPRESS_BASE) /D PLATFORM_PCIEXPRESS_LENGTH=0x$(PLATFORM_PCIEXPRESS_LEN) -DASF_PEI
  *_*_IA32_VFRPP_FLAGS   = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_IA32_APP_FLAGS     = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_IA32_PP_FLAGS      = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_IA32_ASLPP_FLAGS   = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_IA32_NASM_FLAGS    =

  *_*_X64_CC_FLAGS       = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_X64_VFRPP_FLAGS    = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_X64_APP_FLAGS      = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_X64_PP_FLAGS       = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_X64_ASLPP_FLAGS    = $(EDKII_DSC_BUILD_OPTIONS) /D PLATFORM_PCIEXPRESS_BASE=0x$(PLATFORM_PCIEXPRESS_BASE) /D PLATFORM_PCIEXPRESS_LENGTH=0x$(PLATFORM_PCIEXPRESS_LEN)
  *_*_X64_ASLCC_FLAGS    = $(EDKII_DSC_BUILD_OPTIONS) /D PLATFORM_PCIEXPRESS_BASE=0x$(PLATFORM_PCIEXPRESS_BASE) /D PLATFORM_PCIEXPRESS_LENGTH=0x$(PLATFORM_PCIEXPRESS_LEN)
  *_*_X64_NASM_FLAGS     =

