# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\LocalCode\V21_Ngit\ChangeToMemoryDebug_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(296, 81)
        self.label = QtWidgets.QLabel(About)
        self.label.setGeometry(QtCore.QRect(30, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "關於此tool"))
        self.label.setText(_translate("About", "Kevin Liou亂寫的\n"
"   自動修改debug模式 tool v1.0.0"))
