#
# (c) Copyright 2012 - 2025 HP Development Company, L.P.
# This software and associated documentation (if any) is furnished under a license and may only be used or
# copied in accordance with the terms of the license. Except as permitted by such license, no part of this
# software or documentation may be reproduced, stored in a retrieval system, or transmitted in any
# form or by any means without the express written consent of HP Development Company.
#
# Prepare build tokens for EDKII
#

[BuildOptions]

#
# SA
#
!if gSiPkgTokenSpaceGuid.PcdBdatEnable == TRUE
   DEFINE BDAT_BUILD_OPTION = -DBDAT_SUPPORT=1
!else
   DEFINE BDAT_BUILD_OPTION =
!endif

!if gSiPkgTokenSpaceGuid.PcdVtdEnable == TRUE
   DEFINE DSC_VTD_BUILD_OPTIONS = /DVTD_SUPPORT_FLAG=1
!else
   DEFINE DSC_VTD_BUILD_OPTIONS =
!endif

!if gSiPkgTokenSpaceGuid.PcdTxtEnable == TRUE
   DEFINE DSC_TXT_BUILD_OPTIONS = /DTXT_SUPPORT_FLAG=1
!else
   DEFINE DSC_TXT_BUILD_OPTIONS =
!endif

!if gSiPkgTokenSpaceGuid.PcdAmtEnable == TRUE
   DEFINE AMT_BUILD_OPTION = /DAMT_SUPPORT=1
!else
   DEFINE AMT_BUILD_OPTION =
!endif

!if gSiPkgTokenSpaceGuid.PcdPttEnable == TRUE
   DEFINE PTT_BUILD_OPTION = /DPTT_FLAG=1
!else
   DEFINE PTT_BUILD_OPTION =
!endif

!if gSiPkgTokenSpaceGuid.PcdStatusCodeUseTraceHub == TRUE
   DEFINE TRACE_HUB_ENABLE_BUILD_OPTIONS = /DTRACE_HUB_ENABLE=1
   DEFINE TRACE_HUB_DEBUG_BUILD_OPTIONS = /DTRACE_HUB_DEBUG_ENABLE=1
!else
   DEFINE TRACE_HUB_ENABLE_BUILD_OPTIONS =
   DEFINE TRACE_HUB_DEBUG_BUILD_OPTIONS =
!endif

!if gSiPkgTokenSpaceGuid.PcdFspBinaryEnable == FALSE
   DEFINE DSC_FSP_SUPPORT = /DHP_FSP_WRAPPER_FLAG=1 /DFSP_WRAPPER_FLAG=1
!else
   DEFINE DSC_FSP_SUPPORT =
!endif


#
# gHpCommonPkgTokenSpaceGuid
#
!if gEfiHpFeatureMiscPubIntPkgTokenSpaceGuid.PcdVPEnable == TRUE
   DEFINE VP_BUILD_OPTIONS = /DVP_FLAG
!else
   DEFINE VP_BUILD_OPTIONS =
!endif

!if gEfiHpFeatureMiscPubIntPkgTokenSpaceGuid.PcdSLEEnable == TRUE
   DEFINE SLE_BUILD_OPTIONS = /DSLE_FLAG
!else
   DEFINE SLE_BUILD_OPTIONS =
!endif

!if (gEfiHpFeatureMiscPubIntPkgTokenSpaceGuid.PcdSLEEnable == TRUE) OR ($(RELEASE_BUILD_DEBUG) == TRUE)
   DEFINE PDB_BUILD_OPTION = /Zi
!else
   DEFINE PDB_BUILD_OPTION =
!endif

!if gHpIntelChipsetPkgTokenSpaceGuid.PcdSerialDebugInAcpiEnable  == TRUE
   DEFINE DSC_SERIAL_DEBUG_SUPPORT = /DSERIAL_DEBUG=1
!else
   DEFINE DSC_SERIAL_DEBUG_SUPPORT =
!endif



#
# gHpIntelChipsetPkgTokenSpaceGuid
#
!if $(TARGET) == RELEASE
  # MDEPKG_NDEBUG is introduced for the intention
  # of size reduction when compiler optimization is disabled. If MDEPKG_NDEBUG is
  # defined, then debug and assert related macros wrapped by it are the NULL implementations.
  DEFINE DEBUG_BUILD_OPTIONS = -DMDEPKG_NDEBUG -DNDEBUG
!else
  DEFINE DEBUG_BUILD_OPTIONS =
!endif

!if gHpIntelChipsetPkgTokenSpaceGuid.PcdIntelRaidModeEnable == TRUE
   DEFINE DSC_INTEL_RAID_BUILD_OPTIONS = /DINTEL_RAID_SUPPORT=1
!else
   DEFINE DSC_INTEL_RAID_BUILD_OPTIONS
!endif

!if gHpIntelChipsetPkgTokenSpaceGuid.PcdHpVtioSupport == TRUE
   DEFINE DSC_HP_VTIO_SUPPORT = /DHP_VTIO_SUPPORT=1
!else
   DEFINE DSC_HP_VTIO_SUPPORT =
!endif

#
# gHpModernStandbyPkgTokenSpaceGuid, gHpMobilePkgTokenSpaceGuid
#
!if gHpModernStandbyPkgTokenSpaceGuid.PcdHpModernStandbySupport == TRUE
   DEFINE DSC_MODERN_STANDBY_SUPPORT = /DHP_MODERN_STANDBY_SUPPORTED
!else
   DEFINE DSC_MODERN_STANDBY_SUPPORT
!endif

!if gEfiBuiltInDeviceOptionsPubIntPkgTokenSpaceGuid.PcdCameraType == 1
  DEFINE DSC_MIPI_FRONT_CAMERA = /DMIPI_FRONT_CAMERA=1
!else
  DEFINE DSC_MIPI_FRONT_CAMERA =
!endif

!if $(GROUP_GPIO_SUPPORT) == TRUE
   DEFINE GROUP_GPIO_BUILD_OPTION = /DGROUP_GPIO=1
!else
   DEFINE GROUP_GPIO_BUILD_OPTION =
!endif

!if $(VTX_ENABLE) == TRUE
   DEFINE DSC_VTX_BUILD_OPTIONS = /DVTX_SUPPORT_FLAG=1
!else
   DEFINE DSC_VTX_BUILD_OPTIONS =
!endif

!if $(HP_ESPI_BUS_SUPPORT) == TRUE
   DEFINE DSC_ESPI_BUS_SUPPORT = /DESPI_BUS_SUPPORT=1
!else
   DEFINE DSC_ESPI_BUS_SUPPORT = /DESPI_BUS_SUPPORT=0
!endif

!if $(OFFICIAL_RELEASE) == TRUE
   DEFINE DSC_SIGNING_KEYS   = /DOFFICIAL_RELEASE=1 /DSECURITY_FLAGS_INCLUDED
!else
   DEFINE DSC_SIGNING_KEYS   = /DOFFICIAL_RELEASE=0 /DSECURITY_FLAGS_INCLUDED
!endif

!if $(MISC_MOBLIE_KBC_DEV_CONFIG_SUPPORT) == TRUE
   DEFINE MISC_MOBLIE_KBC_DEV_CONFIG_SUPPORT   = /DMISC_MOBLIE_KBC_DEV_CONFIG_SUPPORT=1
!else
   DEFINE MISC_MOBLIE_KBC_DEV_CONFIG_SUPPORT   = /DMISC_MOBLIE_KBC_DEV_CONFIG_SUPPORT=0
!endif

!if $(NETCLONE_SUPPORT) == TRUE
   DEFINE DSC_NETCLONE_SUPPORT   = /DNETCLONE_SUPPORT=1
   !if $(HP_NET_CLONE_EFI_SUPPORT) == TRUE
      DEFINE DSC_HP_NET_CLONE_EFI_SUPPORT = /DHP_NET_CLONE_EFI_SUPPORT=1
   !else
      DEFINE DSC_HP_NET_CLONE_EFI_SUPPORT = /DHP_NET_CLONE_EFI_SUPPORT=0
   !endif
!else
   DEFINE DSC_NETCLONE_SUPPORT   = /DNETCLONE_SUPPORT=0
   DEFINE DSC_HP_NET_CLONE_EFI_SUPPORT = /DHP_NET_CLONE_EFI_SUPPORT=0
!endif

!if $(CONNECTED_BIOS_ENABLED) == TRUE
   DEFINE DSC_CONNECTED_BIOS_ENABLED   = /DCONNECTED_BIOS_ENABLED=1
!else
   DEFINE DSC_CONNECTED_BIOS_ENABLED   = /DCONNECTED_BIOS_ENABLED=0
!endif

!if $(HP_WAKE_ON_LAN_SUPPORT) == TRUE
   DEFINE DSC_HP_WAKE_ON_LAN_SUPPORT = /DHP_WAKE_ON_LAN_SUPPORT=1
!else
   DEFINE DSC_HP_WAKE_ON_LAN_SUPPORT =
!endif

!if $(DEBUG_BIOS_ENABLE) == TRUE
   DEFINE DEBUG_BUILD_OPTIONS = /DEFI_DEBUG /DDEBUG_MODE=1
!endif

!if $(EFI_GENERATE_INTERMEDIATE_FILE) == TRUE
   DEFINE DSC_INTERMEDIATE_FILE = /FAsc
!else
   DEFINE DSC_INTERMEDIATE_FILE =
!endif

!if $(USB_TYPE_C_SUPPORT) == TRUE
   DEFINE DSC_USB_TYPE_C_SUPPORT_OPTIONS = /DUSB_TYPE_C_SUPPORT=1
!else
   DEFINE DSC_USB_TYPE_C_SUPPORT_OPTIONS = /DUSB_TYPE_C_SUPPORT=0
!endif

!if $(HP_USB_TYPE_C_CCG4_SUPPORT) == TRUE
   DEFINE DSC_HP_USB_TYPE_C_CCG4_SUPPORT_OPTIONS = /DHP_USB_TYPE_C_CCG4_SUPPORT=1
!else
   DEFINE DSC_HP_USB_TYPE_C_CCG4_SUPPORT_OPTIONS = /DHP_USB_TYPE_C_CCG4_SUPPORT=0
!endif

!if $(FINGERPRINT_SUPPORT) == TRUE
   DEFINE DSC_FINGERPRINT_SUPPORT = /DFINGERPRINT_SUPPORT=1
!else
   DEFINE DSC_FINGERPRINT_SUPPORT = /DFINGERPRINT_SUPPORT=0
!endif

!if $(DUST_FILTER_SUPPORT) == TRUE
   DEFINE DSC_DUST_FILTER_SUPPORT = /DDUST_FILTER_SUPPORT=1
!else
   DEFINE DSC_DUST_FILTER_SUPPORT = /DDUST_FILTER_SUPPORT=0
!endif

!if $(RESTRICT_USB_DEVICES_SUPPORT) == TRUE
   DEFINE DSC_RESTRICT_USB_DEVICES_SUPPORT = /DRESTRICT_USB_DEVICES_SUPPORT=1
!else
   DEFINE DSC_RESTRICT_USB_DEVICES_SUPPORT = /DRESTRICT_USB_DEVICES_SUPPORT=0
!endif

!if $(UCSI_SUPPORT) == TRUE
   DEFINE DSC_UCSI_SUPPORT = /DUCSI_SUPPORT=1
!else
   DEFINE DSC_UCSI_SUPPORT = /DUCSI_SUPPORT=0
!endif

!if $(AMP_SUPPORT) == TRUE
   DEFINE DSC_AMP_SUPPORT = /DAMP_SUPPORT=1
!else
   DEFINE DSC_AMP_SUPPORT = /DAMP_SUPPORT=0
!endif

!if $(HP_VPM_SUPPORT) == TRUE
   DEFINE DSC_HP_VPM_SUPPORT_OPTIONS = /DHP_VPM_SUPPORT=1
!else
   DEFINE DSC_HP_VPM_SUPPORT_OPTIONS = /DHP_VPM_SUPPORT=0
!endif

!if $(HP_SUPER_VPM_SUPPORT) == TRUE
   DEFINE DSC_HP_SUPER_VPM_SUPPORT_OPTIONS = /DHP_SUPER_VPM_SUPPORT=1
!else
   DEFINE DSC_HP_SUPER_VPM_SUPPORT_OPTIONS = /DHP_SUPER_VPM_SUPPORT=0
!endif

!if $(HP_SIO_PRIVACY_PANEL_SUPPORT) == TRUE
   DEFINE DSC_HP_SIO_PRIVACY_PANEL_SUPPORT = /DHP_SIO_PRIVACY_PANEL_SUPPORT=1
!else
   DEFINE DSC_HP_SIO_PRIVACY_PANEL_SUPPORT =
!endif

!ifdef SPI_ROM_SIZE
   DEFINE DSC_SPI_ROM_SIZE = /DSPI_ROM_SIZE=$(SPI_ROM_SIZE)
!endif

!ifdef BIOS_REGION_SIZE
   DEFINE DSC_BIOS_REGION_SIZE = /DBIOS_REGION_SIZE=$(BIOS_REGION_SIZE)
!endif

!if $(INTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT) == TRUE
   DEFINE DSC_INTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT = /DINTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT=1
!else
   DEFINE DSC_INTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT = /DINTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT=0
!endif

!if $(INTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT) == TRUE
   DEFINE DSC_INTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT = /DINTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT=1
!else
   DEFINE DSC_INTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT = /DINTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT=0
!endif

!include NetworkPkg/NetworkBuildOptions.dsc.inc

!if gSiPkgTokenSpaceGuid.PcdSourceDebugEnable == TRUE
   *_*_X64_GENFW_FLAGS  = --keepexceptiontable
!endif

!if gMinPlatformPkgTokenSpaceGuid.PcdMaxCpuSocketCount == 1
  DEFINE MAX_SOCKET_OPTION = /DMAX_SOCKET=1
!else
  DEFINE MAX_SOCKET_OPTION
!endif

# Build option for LNL SOC Core Boot
!if gSiPkgTokenSpaceGuid.PcdSocCoreBootEnable == TRUE
  DEFINE SOC_CORE_BUILD_OPTIONS = -DSOC_CORE_BOOT
!else
  DEFINE SOC_CORE_BUILD_OPTIONS =
!endif

!if $(HP_DOCK_SUPPORT) == TRUE
   DEFINE DOCK_BUILD_OPTION = /DDOCK_SUPPORT=1
!else
   DEFINE DOCK_BUILD_OPTION =
!endif

!if $(HP_MEMORY_DOWN_SUPPORT) == TRUE
   DEFINE MEMORY_DOWN_OPTION = /DMEMORY_DOWN_SUPPORT=1
!else
   DEFINE MEMORY_DOWN_OPTION =
!endif

!if gSiPkgTokenSpaceGuid.PcdBootGuardEnable == TRUE
   DEFINE HP_BOOT_GUARD = /DBOOTGUARD_ENABLED=1
!else
   DEFINE HP_BOOT_GUARD =
!endif

!if $(MICROSOFTTEAMSROOMS_SUPPORT) == TRUE
   DEFINE DSC_MICROSOFTTEAMSROOMS_SUPPORT = /DMICROSOFTTEAMSROOMS_SUPPORT=1
!else
   DEFINE DSC_MICROSOFTTEAMSROOMS_SUPPORT = /DMICROSOFTTEAMSROOMS_SUPPORT=0
!endif

## 4K alignment for DXE image protection
[BuildOptions.common.EDKII.DXE_CORE,BuildOptions.common.EDKII.DXE_DRIVER,BuildOptions.common.EDKII.UEFI_DRIVER,BuildOptions.common.EDKII.UEFI_APPLICATION]
  MSFT:*_*_*_DLINK_FLAGS = /ALIGN:4096

## 4K alignment for UEFI NX/ RT memory attributes table
[BuildOptions.common.EDKII.DXE_RUNTIME_DRIVER]
   MSFT:*_*_*_DLINK_FLAGS = /ALIGN:4096

## 4K alignment for SS3 / SMM memory attributes table
[BuildOptions.X64.EDKII.DXE_SMM_DRIVER]
   MSFT:*_*_*_DLINK_FLAGS = /ALIGN:4096

## 4K alignment for SS3 / SMM memory attributes table
[BuildOptions.X64.EDKII.SMM_CORE]
   MSFT:*_*_*_DLINK_FLAGS = /ALIGN:4096

# Set the Build Options for network drivers.
!if $(CONNECTED_BIOS_ENABLED) == TRUE
[BuildOptions.common]
   MSFT:*_*_*_CC_FLAGS = /DINCLUDE_DRIVER_BINDING
#  GCC:*_*_*_CC_FLAGS =
!endif

# Set the Build Options for EDKII drivers.
[BuildOptions.Common.EDKII]
   !include $(HP_CORE)/HpCoreBuildOptions.dsc
   !include $(HP_FEATURE)/HpFeatureBuildOptions.dsc
   !include $(HP_CHIPSET_PACKAGE)/HpFeature/HpFeatureChipsetBuildOptions.dsc
!if $(RELEASE_BUILD_DEBUG) == TRUE
   RELEASE_*_*_DLINK_FLAGS = /DEBUG
!endif

#
# For Xcode Specific Build Flag
#
# Override assembly code build order
*_XCODE5_*_*_BUILDRULEORDER = nasm S s
# Align 47bfbd7f8069e523798ef973c8eb0abd5c6b0746 to fix the usage of VA_START in undefined way
*_XCODE5_*_CC_FLAGS = -Wno-varargs


  DEFINE DSC_SIPKG_FEATURE_BUILD_OPTIONS = $(BDAT_BUILD_OPTION) $(DEBUG_BUILD_OPTIONS) $(PTT_BUILD_OPTION) $(DSC_FSP_SUPPORT) $(MAX_SOCKET_OPTION) $(SOC_CORE_BUILD_OPTIONS)

  DEFINE PCD_CONFIG_BUILD_OPTIONS = $(INTEL_CHIPSET_ACPI_PATH) $(HP_TBT_BUILD_OPTIONS) $(CONDEV_ACPI_PATH) $(THERMAL_ACPI_PATH) $(HP_DPTF_BUILD_OPTION) $(HP_EXS_SENSOR_BUILD_OPTION) $(DMAR_PKG_BUILD_OPTIONS)
  DEFINE BIOS_BUILD_OPTIONS = $(PCD_CONFIG_BUILD_OPTIONS) $(PTT_BUILD_OPTION) $(AMT_BUILD_OPTION) $(GROUP_GPIO_BUILD_OPTION) $(DOCK_BUILD_OPTION) $(MEMORY_DOWN_OPTION) $(HP_BOOT_GUARD)

  DEFINE HP_MULTI_PROJECT_BUILD_OPTIONS = /DHP_PROJECT_INDEX=$(HP_PROJECT_INDEX) $(HP_PROJECT_DEFINITION) /DHP_SERIES=$(HP_SERIES) $(HP_SERIES_DEFINITION)

  DEFINE DSC_HP_COMMON_BUILD_OPTIONS = $(DSC_SPI_ROM_SIZE) $(DSC_BIOS_REGION_SIZE) $(HP_MULTI_PROJECT_BUILD_OPTIONS) $(DSC_HP_EPSC_BUILD_OPTION) $(DSC_INTERMEDIATE_FILE) $(DSC_SIGNING_KEYS) $(DSC_NETCLONE_SUPPORT) $(DSC_CONNECTED_BIOS_ENABLED) $(DSC_HP_NET_CLONE_EFI_SUPPORT) $(MISC_MOBLIE_KBC_DEV_CONFIG_SUPPORT) $(DSC_INTEL_RAID_BUILD_OPTIONS) $(DSC_ESPI_BUS_SUPPORT) $(DSC_RESTRICT_USB_DEVICES_SUPPORT) $(DSC_FINGERPRINT_SUPPORT) $(DSC_USB_TYPE_C_SUPPORT_OPTIONS) $(DSC_HP_USB_TYPE_C_CCG4_SUPPORT_OPTIONS) $(DSC_MODERN_STANDBY_SUPPORT) $(DSC_HP_MICROPHONE_LOCK_MODE) $(DSC_MIPI_FRONT_CAMERA) $(DSC_UCSI_SUPPORT) $(DSC_HP_VTIO_SUPPORT) $(DSC_AMP_SUPPORT) $(DSC_HP_SURE_SHUTTER_SUPPORT) $(HP_MSHZ_BUILD_OPTION) $(DSC_INTEL_DGR_IO_PORT_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT) $(DSC_INTEL_DGR_MSR_ALLOW_ACCESS_IN_SMN_AFTER_END_OF_DXE_SUPPORT) $(DSC_DUST_FILTER_SUPPORT) $(DSC_DT_BUILD_OPTIONS) $(DSC_HP_VPM_SUPPORT_OPTIONS) $(DSC_HP_SUPER_VPM_SUPPORT_OPTIONS) $(DSC_MICROSOFTTEAMSROOMS_SUPPORT)
  DEFINE DSC_HP_EDKII_BUILD_OPTIONS =  $(DSC_MODERN_STANDBY_SUPPORT) $(DSC_PLTPKG_FEATURE_BUILD_OPTIONS) $(DSC_SERIAL_DEBUG_SUPPORT)

  DEFINE DSC_HP_FEATURE_PLATFORM_BUILD_OPTIONS = $(DSC_SYSTEM_OPTIONS_PLATFORM_BUILD_OPTIONS) $(DSC_PORT_OPTIONS_PLATFORM_BUILD_OPTIONS) $(DSC_POWER_MANAGEMENT_PLATFORM_BUILD_OPTIONS) $(DSC_HP_GFX_MISC_PLATFORM_BUILD_OPTIONS) $(DSC_HP_BRIGHTNESS_PLATFORM_BUILD_OPTIONS) $(DSC_INTEL_HYBRID_GRAPHICS_PLATFORM_BUILD_OPTIONS) $(DSC_ADDON_GFX_POLICY_PLATFORM_BUILD_OPTIONS) $(DSC_AIO_GFX_POLICY_PLATFORM_BUILD_OPTIONS)

  DEFINE SV_EDKII_BUILD_OPTIONS = $(DSC_SIPKG_FEATURE_BUILD_OPTIONS) $(DSC_HP_CORE_BUILD_OPTIONS) $(DSC_HP_FEATURE_BUILD_OPTIONS) $(DSC_HP_FEATURE_CHIPSET_BUILD_OPTIONS) $(DSC_HP_FEATURE_PLATFORM_BUILD_OPTIONS) $(DSC_HP_COMMON_BUILD_OPTIONS) $(DSC_HP_EDKII_BUILD_OPTIONS)
  DEFINE EDK_EDKII_DSC_FEATURE_BUILD_OPTIONS = $(PDB_BUILD_OPTION) $(TEST_MENU_BUILD_OPTION) $(VP_BUILD_OPTIONS) $(SLE_BUILD_OPTIONS) $(BIOS_BUILD_OPTIONS) $(DSC_VTX_BUILD_OPTIONS) $(DSC_VTD_BUILD_OPTIONS) $(DSC_TXT_BUILD_OPTIONS) $(TRACE_HUB_DEBUG_BUILD_OPTIONS)
  DEFINE EDKII_DSC_BUILD_OPTIONS = $(EDK_EDKII_DSC_FEATURE_BUILD_OPTIONS) $(SV_EDKII_BUILD_OPTIONS)

  *_*_IA32_ASM_FLAGS     = $(VP_BUILD_OPTIONS) $(BIOS_BUILD_OPTIONS) $(SLE_BUILD_OPTIONS) /D PLATFORM_PCIEXPRESS_LENGTH=$(PLATFORM_PCIEXPRESS_LEN)h /D EDKII_GLUE_PciExpressBaseAddress=$(PLATFORM_PCIEXPRESS_BASE)h /D PCIEX_LENGTH_BIT_SETTING=$(PLATFORM_PCIEX_LENGTH_BIT_SETTING)b $(DSC_P21_SUPPORT) $(ANC_BUILD_OPTIONS)

  *_*_IA32_CC_FLAGS      = $(EDKII_DSC_BUILD_OPTIONS) /D PLATFORM_PCIEXPRESS_BASE=0x$(PLATFORM_PCIEXPRESS_BASE) /D PLATFORM_PCIEXPRESS_LENGTH=0x$(PLATFORM_PCIEXPRESS_LEN) -DASF_PEI
  *_*_IA32_VFRPP_FLAGS   = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_IA32_APP_FLAGS     = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_IA32_PP_FLAGS      = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_IA32_ASLPP_FLAGS   = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_IA32_NASM_FLAGS    =

  *_*_X64_ASM_FLAGS     = $(VP_BUILD_OPTIONS) $(BIOS_BUILD_OPTIONS) $(SLE_BUILD_OPTIONS) /D PLATFORM_PCIEXPRESS_LENGTH=$(PLATFORM_PCIEXPRESS_LEN)h /D EDKII_GLUE_PciExpressBaseAddress=$(PLATFORM_PCIEXPRESS_BASE)h /D PCIEX_LENGTH_BIT_SETTING=$(PLATFORM_PCIEX_LENGTH_BIT_SETTING)b $(DSC_P21_SUPPORT) $(ANC_BUILD_OPTIONS)

  *_*_X64_CC_FLAGS       = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_X64_VFRPP_FLAGS    = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_X64_APP_FLAGS      = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_X64_PP_FLAGS       = $(EDKII_DSC_BUILD_OPTIONS)
  *_*_X64_ASLPP_FLAGS    = $(EDKII_DSC_BUILD_OPTIONS) /D PLATFORM_PCIEXPRESS_BASE=0x$(PLATFORM_PCIEXPRESS_BASE) /D PLATFORM_PCIEXPRESS_LENGTH=0x$(PLATFORM_PCIEXPRESS_LEN)
  *_*_X64_ASLCC_FLAGS    = $(EDKII_DSC_BUILD_OPTIONS) /D PLATFORM_PCIEXPRESS_BASE=0x$(PLATFORM_PCIEXPRESS_BASE) /D PLATFORM_PCIEXPRESS_LENGTH=0x$(PLATFORM_PCIEXPRESS_LEN)
  *_*_X64_NASM_FLAGS     =

